GET http://localhost:3000/productos 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZFVzdWFyaW8iOjIsImNyZWF0ZWRBdCI6MTYwMDY4MjMzNDgyNCwiZXhwaXJlZEF0Ijo4MDAzNDQ3NjcsImlhdCI6MTYwMDY4MjMzNH0.0lA7SQge-YTwUmYKQWunjDn5rLsiG0bGyyWqrSQtCBI

###

POST http://localhost:3000/productos
Content-Type: application/json

{
    "nombre": "Camara",
    "descripcion": "Camara fotos años 1980",
    "imagen": null,
}


###

DELETE http://localhost:3000/delete/ 
Content-Type: application/json
{
    "id": 1
}

### secciones ####
GET http://localhost:3000/secciones


### USUARIOS
POST http://localhost:3000/usuarios/registro 
Content-Type: application/json

{
    "username": "morales", "email": "cristianmorales@neoland.com", "password": "789"

}

### 
POST http://localhost:3000/usuarios/login 
Content-Type: application/json

{
    "email": "cristian@neoland.com", "password": "456"

}
